plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
locale: "hu_HU"
title: "Fenntartható Heves" # the name of your site, e.g. ACME Corp.
tagline: "Egy élhető mintaprojekt"
email: fenntarthato.heves@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Fenntartható Heves - Egy élhető mintaprojekt
author: Fenntartható Heves
url: "http://fenntarthato-heves.hu" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
google_analytics: G-0QT62ZJ8PQ
# twitter:
#   username:
#   card: summary #keep this to generate a twitter share card
